
replicaCount: 2

image:
  repository: thashenu/portfolio
  pullPolicy: IfNotPresent
  tag: "15247346831"


ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
 